### ISSUE TITLE
Jak można robić boty w DBM i się tym chwalić

### ISSUE THREAD

**Issue by see-ocean** [Aleksio1123/sigma#2]
**Jak można robić boty w DBM i się tym chwalić **

**Comment by Pazdikan** [comment]
to nie jego bot

**Comment by see-ocean** [comment]
I tak publikowanie tego to...

**Comment by Pazdikan** [comment]
no aleks pisze bota w js a ten od sigmy w dbm kopiuje np wyglad (p)help albo robi te same akcje

**Comment by Aleksio1123** [comment]
To jest bot sigma uzytkownika  Sebkowy#3728 (`464308779866128392`) ktory zaczal kopiowac stare funkcj emojego bota i zostaw wstawiony tu 

Zamykam
